//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.16 at 01:00:04 PM EET 
//


package se.snabbfoto.ejb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for faceImageQuality complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="faceImageQuality"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="centeredQuality" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="contrastQuality" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="croppingQuality" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="eyesClearQuality" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="facenessQuality" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="focusQuality" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="glareQuality" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="headSizeQuality" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="overExposureQuality" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="overallQuality" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="textureQuality" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="underExposureQuality" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "faceImageQuality", propOrder = {
    "centeredQuality",
    "contrastQuality",
    "croppingQuality",
    "eyesClearQuality",
    "facenessQuality",
    "focusQuality",
    "glareQuality",
    "headSizeQuality",
    "overExposureQuality",
    "overallQuality",
    "textureQuality",
    "underExposureQuality"
})
@XmlSeeAlso({
    FaceImageQualityExtended.class
})
public class FaceImageQuality
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    protected double centeredQuality;
    protected double contrastQuality;
    protected double croppingQuality;
    protected double eyesClearQuality;
    protected double facenessQuality;
    protected double focusQuality;
    protected double glareQuality;
    protected double headSizeQuality;
    protected double overExposureQuality;
    protected double overallQuality;
    protected double textureQuality;
    protected double underExposureQuality;

    /**
     * Gets the value of the centeredQuality property.
     * 
     */
    public double getCenteredQuality() {
        return centeredQuality;
    }

    /**
     * Sets the value of the centeredQuality property.
     * 
     */
    public void setCenteredQuality(double value) {
        this.centeredQuality = value;
    }

    /**
     * Gets the value of the contrastQuality property.
     * 
     */
    public double getContrastQuality() {
        return contrastQuality;
    }

    /**
     * Sets the value of the contrastQuality property.
     * 
     */
    public void setContrastQuality(double value) {
        this.contrastQuality = value;
    }

    /**
     * Gets the value of the croppingQuality property.
     * 
     */
    public double getCroppingQuality() {
        return croppingQuality;
    }

    /**
     * Sets the value of the croppingQuality property.
     * 
     */
    public void setCroppingQuality(double value) {
        this.croppingQuality = value;
    }

    /**
     * Gets the value of the eyesClearQuality property.
     * 
     */
    public double getEyesClearQuality() {
        return eyesClearQuality;
    }

    /**
     * Sets the value of the eyesClearQuality property.
     * 
     */
    public void setEyesClearQuality(double value) {
        this.eyesClearQuality = value;
    }

    /**
     * Gets the value of the facenessQuality property.
     * 
     */
    public double getFacenessQuality() {
        return facenessQuality;
    }

    /**
     * Sets the value of the facenessQuality property.
     * 
     */
    public void setFacenessQuality(double value) {
        this.facenessQuality = value;
    }

    /**
     * Gets the value of the focusQuality property.
     * 
     */
    public double getFocusQuality() {
        return focusQuality;
    }

    /**
     * Sets the value of the focusQuality property.
     * 
     */
    public void setFocusQuality(double value) {
        this.focusQuality = value;
    }

    /**
     * Gets the value of the glareQuality property.
     * 
     */
    public double getGlareQuality() {
        return glareQuality;
    }

    /**
     * Sets the value of the glareQuality property.
     * 
     */
    public void setGlareQuality(double value) {
        this.glareQuality = value;
    }

    /**
     * Gets the value of the headSizeQuality property.
     * 
     */
    public double getHeadSizeQuality() {
        return headSizeQuality;
    }

    /**
     * Sets the value of the headSizeQuality property.
     * 
     */
    public void setHeadSizeQuality(double value) {
        this.headSizeQuality = value;
    }

    /**
     * Gets the value of the overExposureQuality property.
     * 
     */
    public double getOverExposureQuality() {
        return overExposureQuality;
    }

    /**
     * Sets the value of the overExposureQuality property.
     * 
     */
    public void setOverExposureQuality(double value) {
        this.overExposureQuality = value;
    }

    /**
     * Gets the value of the overallQuality property.
     * 
     */
    public double getOverallQuality() {
        return overallQuality;
    }

    /**
     * Sets the value of the overallQuality property.
     * 
     */
    public void setOverallQuality(double value) {
        this.overallQuality = value;
    }

    /**
     * Gets the value of the textureQuality property.
     * 
     */
    public double getTextureQuality() {
        return textureQuality;
    }

    /**
     * Sets the value of the textureQuality property.
     * 
     */
    public void setTextureQuality(double value) {
        this.textureQuality = value;
    }

    /**
     * Gets the value of the underExposureQuality property.
     * 
     */
    public double getUnderExposureQuality() {
        return underExposureQuality;
    }

    /**
     * Sets the value of the underExposureQuality property.
     * 
     */
    public void setUnderExposureQuality(double value) {
        this.underExposureQuality = value;
    }

}
