//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.16 at 01:00:04 PM EET 
//


package se.snabbfoto.ejb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for faceImageQualityExtended complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="faceImageQualityExtended"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://ejb.snabbfoto.se/}faceImageQuality"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="backgroundBrightness" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="backgroundShadows" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="backgroundUniformity" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="exposure" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="eyesOpen" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="facialShadows" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="frontalPose" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="hotSpots" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="overExposed" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="shadowsInEyeSockets" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="sunGlasses" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="uniformLighting" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="unnaturalColor" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "faceImageQualityExtended", propOrder = {
    "backgroundBrightness",
    "backgroundShadows",
    "backgroundUniformity",
    "exposure",
    "eyesOpen",
    "facialShadows",
    "frontalPose",
    "hotSpots",
    "overExposed",
    "shadowsInEyeSockets",
    "sunGlasses",
    "uniformLighting",
    "unnaturalColor"
})
public class FaceImageQualityExtended
    extends FaceImageQuality
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    protected double backgroundBrightness;
    protected double backgroundShadows;
    protected double backgroundUniformity;
    protected double exposure;
    protected double eyesOpen;
    protected double facialShadows;
    protected double frontalPose;
    protected double hotSpots;
    protected boolean overExposed;
    protected double shadowsInEyeSockets;
    protected double sunGlasses;
    protected double uniformLighting;
    protected double unnaturalColor;

    /**
     * Gets the value of the backgroundBrightness property.
     * 
     */
    public double getBackgroundBrightness() {
        return backgroundBrightness;
    }

    /**
     * Sets the value of the backgroundBrightness property.
     * 
     */
    public void setBackgroundBrightness(double value) {
        this.backgroundBrightness = value;
    }

    /**
     * Gets the value of the backgroundShadows property.
     * 
     */
    public double getBackgroundShadows() {
        return backgroundShadows;
    }

    /**
     * Sets the value of the backgroundShadows property.
     * 
     */
    public void setBackgroundShadows(double value) {
        this.backgroundShadows = value;
    }

    /**
     * Gets the value of the backgroundUniformity property.
     * 
     */
    public double getBackgroundUniformity() {
        return backgroundUniformity;
    }

    /**
     * Sets the value of the backgroundUniformity property.
     * 
     */
    public void setBackgroundUniformity(double value) {
        this.backgroundUniformity = value;
    }

    /**
     * Gets the value of the exposure property.
     * 
     */
    public double getExposure() {
        return exposure;
    }

    /**
     * Sets the value of the exposure property.
     * 
     */
    public void setExposure(double value) {
        this.exposure = value;
    }

    /**
     * Gets the value of the eyesOpen property.
     * 
     */
    public double getEyesOpen() {
        return eyesOpen;
    }

    /**
     * Sets the value of the eyesOpen property.
     * 
     */
    public void setEyesOpen(double value) {
        this.eyesOpen = value;
    }

    /**
     * Gets the value of the facialShadows property.
     * 
     */
    public double getFacialShadows() {
        return facialShadows;
    }

    /**
     * Sets the value of the facialShadows property.
     * 
     */
    public void setFacialShadows(double value) {
        this.facialShadows = value;
    }

    /**
     * Gets the value of the frontalPose property.
     * 
     */
    public double getFrontalPose() {
        return frontalPose;
    }

    /**
     * Sets the value of the frontalPose property.
     * 
     */
    public void setFrontalPose(double value) {
        this.frontalPose = value;
    }

    /**
     * Gets the value of the hotSpots property.
     * 
     */
    public double getHotSpots() {
        return hotSpots;
    }

    /**
     * Sets the value of the hotSpots property.
     * 
     */
    public void setHotSpots(double value) {
        this.hotSpots = value;
    }

    /**
     * Gets the value of the overExposed property.
     * 
     */
    public boolean isOverExposed() {
        return overExposed;
    }

    /**
     * Sets the value of the overExposed property.
     * 
     */
    public void setOverExposed(boolean value) {
        this.overExposed = value;
    }

    /**
     * Gets the value of the shadowsInEyeSockets property.
     * 
     */
    public double getShadowsInEyeSockets() {
        return shadowsInEyeSockets;
    }

    /**
     * Sets the value of the shadowsInEyeSockets property.
     * 
     */
    public void setShadowsInEyeSockets(double value) {
        this.shadowsInEyeSockets = value;
    }

    /**
     * Gets the value of the sunGlasses property.
     * 
     */
    public double getSunGlasses() {
        return sunGlasses;
    }

    /**
     * Sets the value of the sunGlasses property.
     * 
     */
    public void setSunGlasses(double value) {
        this.sunGlasses = value;
    }

    /**
     * Gets the value of the uniformLighting property.
     * 
     */
    public double getUniformLighting() {
        return uniformLighting;
    }

    /**
     * Sets the value of the uniformLighting property.
     * 
     */
    public void setUniformLighting(double value) {
        this.uniformLighting = value;
    }

    /**
     * Gets the value of the unnaturalColor property.
     * 
     */
    public double getUnnaturalColor() {
        return unnaturalColor;
    }

    /**
     * Sets the value of the unnaturalColor property.
     * 
     */
    public void setUnnaturalColor(double value) {
        this.unnaturalColor = value;
    }

}
