//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.16 at 04:31:58 PM EET 
//


package se.snabbfoto.ejb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fingerprintDeviceInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fingerprintDeviceInformation"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="horizontalLines" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="horizontalResolution" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="impressionType" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="pixelDepth" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="verticalLines" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="verticalResolution" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fingerprintDeviceInformation", propOrder = {
    "horizontalLines",
    "horizontalResolution",
    "impressionType",
    "pixelDepth",
    "verticalLines",
    "verticalResolution"
})
public class FingerprintDeviceInformation
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    protected int horizontalLines;
    protected int horizontalResolution;
    protected int impressionType;
    protected int pixelDepth;
    protected int verticalLines;
    protected int verticalResolution;

    /**
     * Gets the value of the horizontalLines property.
     * 
     */
    public int getHorizontalLines() {
        return horizontalLines;
    }

    /**
     * Sets the value of the horizontalLines property.
     * 
     */
    public void setHorizontalLines(int value) {
        this.horizontalLines = value;
    }

    /**
     * Gets the value of the horizontalResolution property.
     * 
     */
    public int getHorizontalResolution() {
        return horizontalResolution;
    }

    /**
     * Sets the value of the horizontalResolution property.
     * 
     */
    public void setHorizontalResolution(int value) {
        this.horizontalResolution = value;
    }

    /**
     * Gets the value of the impressionType property.
     * 
     */
    public int getImpressionType() {
        return impressionType;
    }

    /**
     * Sets the value of the impressionType property.
     * 
     */
    public void setImpressionType(int value) {
        this.impressionType = value;
    }

    /**
     * Gets the value of the pixelDepth property.
     * 
     */
    public int getPixelDepth() {
        return pixelDepth;
    }

    /**
     * Sets the value of the pixelDepth property.
     * 
     */
    public void setPixelDepth(int value) {
        this.pixelDepth = value;
    }

    /**
     * Gets the value of the verticalLines property.
     * 
     */
    public int getVerticalLines() {
        return verticalLines;
    }

    /**
     * Sets the value of the verticalLines property.
     * 
     */
    public void setVerticalLines(int value) {
        this.verticalLines = value;
    }

    /**
     * Gets the value of the verticalResolution property.
     * 
     */
    public int getVerticalResolution() {
        return verticalResolution;
    }

    /**
     * Sets the value of the verticalResolution property.
     * 
     */
    public void setVerticalResolution(int value) {
        this.verticalResolution = value;
    }

}
