//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.16 at 04:31:58 PM EET 
//


package se.snabbfoto.ejb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fingerprint complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fingerprint"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="leftIndexFingerQuality" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="leftIndexFingerprintJPEG" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="leftIndexFingerprintJPEG2000" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="leftIndexFingerprintWSQ" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="leftLittleFingerQuality" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="leftLittleFingerprintJPEG" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="leftLittleFingerprintJPEG2000" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="leftLittleFingerprintWSQ" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="leftMiddleFingerQuality" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="leftMiddleFingerprintJPEG" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="leftMiddleFingerprintJPEG2000" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="leftMiddleFingerprintWSQ" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="leftRingFingerQuality" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="leftRingFingerprintJPEG" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="leftRingFingerprintJPEG2000" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="leftRingFingerprintWSQ" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="leftThumbFingerQuality" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="leftThumbFingerprintJPEG" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="leftThumbFingerprintJPEG2000" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="leftThumbFingerprintWSQ" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="rightIndexFingerQuality" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="rightIndexFingerprintJPEG" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="rightIndexFingerprintJPEG2000" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="rightIndexFingerprintWSQ" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="rightLittleFingerQuality" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="rightLittleFingerprintJPEG" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="rightLittleFingerprintJPEG2000" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="rightLittleFingerprintWSQ" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="rightMiddleFingerQuality" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="rightMiddleFingerprintJPEG" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="rightMiddleFingerprintJPEG2000" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="rightMiddleFingerprintWSQ" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="rightRingFingerQuality" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="rightRingFingerprintJPEG" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="rightRingFingerprintJPEG2000" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="rightRingFingerprintWSQ" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="rightThumbFingerQuality" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="rightThumbFingerprintJPEG" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="rightThumbFingerprintJPEG2000" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="rightThumbFingerprintWSQ" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fingerprint", propOrder = {
    "leftIndexFingerQuality",
    "leftIndexFingerprintJPEG",
    "leftIndexFingerprintJPEG2000",
    "leftIndexFingerprintWSQ",
    "leftLittleFingerQuality",
    "leftLittleFingerprintJPEG",
    "leftLittleFingerprintJPEG2000",
    "leftLittleFingerprintWSQ",
    "leftMiddleFingerQuality",
    "leftMiddleFingerprintJPEG",
    "leftMiddleFingerprintJPEG2000",
    "leftMiddleFingerprintWSQ",
    "leftRingFingerQuality",
    "leftRingFingerprintJPEG",
    "leftRingFingerprintJPEG2000",
    "leftRingFingerprintWSQ",
    "leftThumbFingerQuality",
    "leftThumbFingerprintJPEG",
    "leftThumbFingerprintJPEG2000",
    "leftThumbFingerprintWSQ",
    "rightIndexFingerQuality",
    "rightIndexFingerprintJPEG",
    "rightIndexFingerprintJPEG2000",
    "rightIndexFingerprintWSQ",
    "rightLittleFingerQuality",
    "rightLittleFingerprintJPEG",
    "rightLittleFingerprintJPEG2000",
    "rightLittleFingerprintWSQ",
    "rightMiddleFingerQuality",
    "rightMiddleFingerprintJPEG",
    "rightMiddleFingerprintJPEG2000",
    "rightMiddleFingerprintWSQ",
    "rightRingFingerQuality",
    "rightRingFingerprintJPEG",
    "rightRingFingerprintJPEG2000",
    "rightRingFingerprintWSQ",
    "rightThumbFingerQuality",
    "rightThumbFingerprintJPEG",
    "rightThumbFingerprintJPEG2000",
    "rightThumbFingerprintWSQ"
})
public class Fingerprint
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    protected int leftIndexFingerQuality;
    protected byte[] leftIndexFingerprintJPEG;
    protected byte[] leftIndexFingerprintJPEG2000;
    protected byte[] leftIndexFingerprintWSQ;
    protected int leftLittleFingerQuality;
    protected byte[] leftLittleFingerprintJPEG;
    protected byte[] leftLittleFingerprintJPEG2000;
    protected byte[] leftLittleFingerprintWSQ;
    protected int leftMiddleFingerQuality;
    protected byte[] leftMiddleFingerprintJPEG;
    protected byte[] leftMiddleFingerprintJPEG2000;
    protected byte[] leftMiddleFingerprintWSQ;
    protected int leftRingFingerQuality;
    protected byte[] leftRingFingerprintJPEG;
    protected byte[] leftRingFingerprintJPEG2000;
    protected byte[] leftRingFingerprintWSQ;
    protected int leftThumbFingerQuality;
    protected byte[] leftThumbFingerprintJPEG;
    protected byte[] leftThumbFingerprintJPEG2000;
    protected byte[] leftThumbFingerprintWSQ;
    protected int rightIndexFingerQuality;
    protected byte[] rightIndexFingerprintJPEG;
    protected byte[] rightIndexFingerprintJPEG2000;
    protected byte[] rightIndexFingerprintWSQ;
    protected int rightLittleFingerQuality;
    protected byte[] rightLittleFingerprintJPEG;
    protected byte[] rightLittleFingerprintJPEG2000;
    protected byte[] rightLittleFingerprintWSQ;
    protected int rightMiddleFingerQuality;
    protected byte[] rightMiddleFingerprintJPEG;
    protected byte[] rightMiddleFingerprintJPEG2000;
    protected byte[] rightMiddleFingerprintWSQ;
    protected int rightRingFingerQuality;
    protected byte[] rightRingFingerprintJPEG;
    protected byte[] rightRingFingerprintJPEG2000;
    protected byte[] rightRingFingerprintWSQ;
    protected int rightThumbFingerQuality;
    protected byte[] rightThumbFingerprintJPEG;
    protected byte[] rightThumbFingerprintJPEG2000;
    protected byte[] rightThumbFingerprintWSQ;

    /**
     * Gets the value of the leftIndexFingerQuality property.
     * 
     */
    public int getLeftIndexFingerQuality() {
        return leftIndexFingerQuality;
    }

    /**
     * Sets the value of the leftIndexFingerQuality property.
     * 
     */
    public void setLeftIndexFingerQuality(int value) {
        this.leftIndexFingerQuality = value;
    }

    /**
     * Gets the value of the leftIndexFingerprintJPEG property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getLeftIndexFingerprintJPEG() {
        return leftIndexFingerprintJPEG;
    }

    /**
     * Sets the value of the leftIndexFingerprintJPEG property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setLeftIndexFingerprintJPEG(byte[] value) {
        this.leftIndexFingerprintJPEG = value;
    }

    /**
     * Gets the value of the leftIndexFingerprintJPEG2000 property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getLeftIndexFingerprintJPEG2000() {
        return leftIndexFingerprintJPEG2000;
    }

    /**
     * Sets the value of the leftIndexFingerprintJPEG2000 property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setLeftIndexFingerprintJPEG2000(byte[] value) {
        this.leftIndexFingerprintJPEG2000 = value;
    }

    /**
     * Gets the value of the leftIndexFingerprintWSQ property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getLeftIndexFingerprintWSQ() {
        return leftIndexFingerprintWSQ;
    }

    /**
     * Sets the value of the leftIndexFingerprintWSQ property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setLeftIndexFingerprintWSQ(byte[] value) {
        this.leftIndexFingerprintWSQ = value;
    }

    /**
     * Gets the value of the leftLittleFingerQuality property.
     * 
     */
    public int getLeftLittleFingerQuality() {
        return leftLittleFingerQuality;
    }

    /**
     * Sets the value of the leftLittleFingerQuality property.
     * 
     */
    public void setLeftLittleFingerQuality(int value) {
        this.leftLittleFingerQuality = value;
    }

    /**
     * Gets the value of the leftLittleFingerprintJPEG property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getLeftLittleFingerprintJPEG() {
        return leftLittleFingerprintJPEG;
    }

    /**
     * Sets the value of the leftLittleFingerprintJPEG property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setLeftLittleFingerprintJPEG(byte[] value) {
        this.leftLittleFingerprintJPEG = value;
    }

    /**
     * Gets the value of the leftLittleFingerprintJPEG2000 property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getLeftLittleFingerprintJPEG2000() {
        return leftLittleFingerprintJPEG2000;
    }

    /**
     * Sets the value of the leftLittleFingerprintJPEG2000 property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setLeftLittleFingerprintJPEG2000(byte[] value) {
        this.leftLittleFingerprintJPEG2000 = value;
    }

    /**
     * Gets the value of the leftLittleFingerprintWSQ property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getLeftLittleFingerprintWSQ() {
        return leftLittleFingerprintWSQ;
    }

    /**
     * Sets the value of the leftLittleFingerprintWSQ property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setLeftLittleFingerprintWSQ(byte[] value) {
        this.leftLittleFingerprintWSQ = value;
    }

    /**
     * Gets the value of the leftMiddleFingerQuality property.
     * 
     */
    public int getLeftMiddleFingerQuality() {
        return leftMiddleFingerQuality;
    }

    /**
     * Sets the value of the leftMiddleFingerQuality property.
     * 
     */
    public void setLeftMiddleFingerQuality(int value) {
        this.leftMiddleFingerQuality = value;
    }

    /**
     * Gets the value of the leftMiddleFingerprintJPEG property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getLeftMiddleFingerprintJPEG() {
        return leftMiddleFingerprintJPEG;
    }

    /**
     * Sets the value of the leftMiddleFingerprintJPEG property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setLeftMiddleFingerprintJPEG(byte[] value) {
        this.leftMiddleFingerprintJPEG = value;
    }

    /**
     * Gets the value of the leftMiddleFingerprintJPEG2000 property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getLeftMiddleFingerprintJPEG2000() {
        return leftMiddleFingerprintJPEG2000;
    }

    /**
     * Sets the value of the leftMiddleFingerprintJPEG2000 property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setLeftMiddleFingerprintJPEG2000(byte[] value) {
        this.leftMiddleFingerprintJPEG2000 = value;
    }

    /**
     * Gets the value of the leftMiddleFingerprintWSQ property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getLeftMiddleFingerprintWSQ() {
        return leftMiddleFingerprintWSQ;
    }

    /**
     * Sets the value of the leftMiddleFingerprintWSQ property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setLeftMiddleFingerprintWSQ(byte[] value) {
        this.leftMiddleFingerprintWSQ = value;
    }

    /**
     * Gets the value of the leftRingFingerQuality property.
     * 
     */
    public int getLeftRingFingerQuality() {
        return leftRingFingerQuality;
    }

    /**
     * Sets the value of the leftRingFingerQuality property.
     * 
     */
    public void setLeftRingFingerQuality(int value) {
        this.leftRingFingerQuality = value;
    }

    /**
     * Gets the value of the leftRingFingerprintJPEG property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getLeftRingFingerprintJPEG() {
        return leftRingFingerprintJPEG;
    }

    /**
     * Sets the value of the leftRingFingerprintJPEG property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setLeftRingFingerprintJPEG(byte[] value) {
        this.leftRingFingerprintJPEG = value;
    }

    /**
     * Gets the value of the leftRingFingerprintJPEG2000 property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getLeftRingFingerprintJPEG2000() {
        return leftRingFingerprintJPEG2000;
    }

    /**
     * Sets the value of the leftRingFingerprintJPEG2000 property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setLeftRingFingerprintJPEG2000(byte[] value) {
        this.leftRingFingerprintJPEG2000 = value;
    }

    /**
     * Gets the value of the leftRingFingerprintWSQ property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getLeftRingFingerprintWSQ() {
        return leftRingFingerprintWSQ;
    }

    /**
     * Sets the value of the leftRingFingerprintWSQ property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setLeftRingFingerprintWSQ(byte[] value) {
        this.leftRingFingerprintWSQ = value;
    }

    /**
     * Gets the value of the leftThumbFingerQuality property.
     * 
     */
    public int getLeftThumbFingerQuality() {
        return leftThumbFingerQuality;
    }

    /**
     * Sets the value of the leftThumbFingerQuality property.
     * 
     */
    public void setLeftThumbFingerQuality(int value) {
        this.leftThumbFingerQuality = value;
    }

    /**
     * Gets the value of the leftThumbFingerprintJPEG property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getLeftThumbFingerprintJPEG() {
        return leftThumbFingerprintJPEG;
    }

    /**
     * Sets the value of the leftThumbFingerprintJPEG property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setLeftThumbFingerprintJPEG(byte[] value) {
        this.leftThumbFingerprintJPEG = value;
    }

    /**
     * Gets the value of the leftThumbFingerprintJPEG2000 property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getLeftThumbFingerprintJPEG2000() {
        return leftThumbFingerprintJPEG2000;
    }

    /**
     * Sets the value of the leftThumbFingerprintJPEG2000 property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setLeftThumbFingerprintJPEG2000(byte[] value) {
        this.leftThumbFingerprintJPEG2000 = value;
    }

    /**
     * Gets the value of the leftThumbFingerprintWSQ property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getLeftThumbFingerprintWSQ() {
        return leftThumbFingerprintWSQ;
    }

    /**
     * Sets the value of the leftThumbFingerprintWSQ property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setLeftThumbFingerprintWSQ(byte[] value) {
        this.leftThumbFingerprintWSQ = value;
    }

    /**
     * Gets the value of the rightIndexFingerQuality property.
     * 
     */
    public int getRightIndexFingerQuality() {
        return rightIndexFingerQuality;
    }

    /**
     * Sets the value of the rightIndexFingerQuality property.
     * 
     */
    public void setRightIndexFingerQuality(int value) {
        this.rightIndexFingerQuality = value;
    }

    /**
     * Gets the value of the rightIndexFingerprintJPEG property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getRightIndexFingerprintJPEG() {
        return rightIndexFingerprintJPEG;
    }

    /**
     * Sets the value of the rightIndexFingerprintJPEG property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setRightIndexFingerprintJPEG(byte[] value) {
        this.rightIndexFingerprintJPEG = value;
    }

    /**
     * Gets the value of the rightIndexFingerprintJPEG2000 property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getRightIndexFingerprintJPEG2000() {
        return rightIndexFingerprintJPEG2000;
    }

    /**
     * Sets the value of the rightIndexFingerprintJPEG2000 property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setRightIndexFingerprintJPEG2000(byte[] value) {
        this.rightIndexFingerprintJPEG2000 = value;
    }

    /**
     * Gets the value of the rightIndexFingerprintWSQ property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getRightIndexFingerprintWSQ() {
        return rightIndexFingerprintWSQ;
    }

    /**
     * Sets the value of the rightIndexFingerprintWSQ property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setRightIndexFingerprintWSQ(byte[] value) {
        this.rightIndexFingerprintWSQ = value;
    }

    /**
     * Gets the value of the rightLittleFingerQuality property.
     * 
     */
    public int getRightLittleFingerQuality() {
        return rightLittleFingerQuality;
    }

    /**
     * Sets the value of the rightLittleFingerQuality property.
     * 
     */
    public void setRightLittleFingerQuality(int value) {
        this.rightLittleFingerQuality = value;
    }

    /**
     * Gets the value of the rightLittleFingerprintJPEG property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getRightLittleFingerprintJPEG() {
        return rightLittleFingerprintJPEG;
    }

    /**
     * Sets the value of the rightLittleFingerprintJPEG property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setRightLittleFingerprintJPEG(byte[] value) {
        this.rightLittleFingerprintJPEG = value;
    }

    /**
     * Gets the value of the rightLittleFingerprintJPEG2000 property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getRightLittleFingerprintJPEG2000() {
        return rightLittleFingerprintJPEG2000;
    }

    /**
     * Sets the value of the rightLittleFingerprintJPEG2000 property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setRightLittleFingerprintJPEG2000(byte[] value) {
        this.rightLittleFingerprintJPEG2000 = value;
    }

    /**
     * Gets the value of the rightLittleFingerprintWSQ property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getRightLittleFingerprintWSQ() {
        return rightLittleFingerprintWSQ;
    }

    /**
     * Sets the value of the rightLittleFingerprintWSQ property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setRightLittleFingerprintWSQ(byte[] value) {
        this.rightLittleFingerprintWSQ = value;
    }

    /**
     * Gets the value of the rightMiddleFingerQuality property.
     * 
     */
    public int getRightMiddleFingerQuality() {
        return rightMiddleFingerQuality;
    }

    /**
     * Sets the value of the rightMiddleFingerQuality property.
     * 
     */
    public void setRightMiddleFingerQuality(int value) {
        this.rightMiddleFingerQuality = value;
    }

    /**
     * Gets the value of the rightMiddleFingerprintJPEG property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getRightMiddleFingerprintJPEG() {
        return rightMiddleFingerprintJPEG;
    }

    /**
     * Sets the value of the rightMiddleFingerprintJPEG property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setRightMiddleFingerprintJPEG(byte[] value) {
        this.rightMiddleFingerprintJPEG = value;
    }

    /**
     * Gets the value of the rightMiddleFingerprintJPEG2000 property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getRightMiddleFingerprintJPEG2000() {
        return rightMiddleFingerprintJPEG2000;
    }

    /**
     * Sets the value of the rightMiddleFingerprintJPEG2000 property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setRightMiddleFingerprintJPEG2000(byte[] value) {
        this.rightMiddleFingerprintJPEG2000 = value;
    }

    /**
     * Gets the value of the rightMiddleFingerprintWSQ property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getRightMiddleFingerprintWSQ() {
        return rightMiddleFingerprintWSQ;
    }

    /**
     * Sets the value of the rightMiddleFingerprintWSQ property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setRightMiddleFingerprintWSQ(byte[] value) {
        this.rightMiddleFingerprintWSQ = value;
    }

    /**
     * Gets the value of the rightRingFingerQuality property.
     * 
     */
    public int getRightRingFingerQuality() {
        return rightRingFingerQuality;
    }

    /**
     * Sets the value of the rightRingFingerQuality property.
     * 
     */
    public void setRightRingFingerQuality(int value) {
        this.rightRingFingerQuality = value;
    }

    /**
     * Gets the value of the rightRingFingerprintJPEG property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getRightRingFingerprintJPEG() {
        return rightRingFingerprintJPEG;
    }

    /**
     * Sets the value of the rightRingFingerprintJPEG property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setRightRingFingerprintJPEG(byte[] value) {
        this.rightRingFingerprintJPEG = value;
    }

    /**
     * Gets the value of the rightRingFingerprintJPEG2000 property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getRightRingFingerprintJPEG2000() {
        return rightRingFingerprintJPEG2000;
    }

    /**
     * Sets the value of the rightRingFingerprintJPEG2000 property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setRightRingFingerprintJPEG2000(byte[] value) {
        this.rightRingFingerprintJPEG2000 = value;
    }

    /**
     * Gets the value of the rightRingFingerprintWSQ property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getRightRingFingerprintWSQ() {
        return rightRingFingerprintWSQ;
    }

    /**
     * Sets the value of the rightRingFingerprintWSQ property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setRightRingFingerprintWSQ(byte[] value) {
        this.rightRingFingerprintWSQ = value;
    }

    /**
     * Gets the value of the rightThumbFingerQuality property.
     * 
     */
    public int getRightThumbFingerQuality() {
        return rightThumbFingerQuality;
    }

    /**
     * Sets the value of the rightThumbFingerQuality property.
     * 
     */
    public void setRightThumbFingerQuality(int value) {
        this.rightThumbFingerQuality = value;
    }

    /**
     * Gets the value of the rightThumbFingerprintJPEG property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getRightThumbFingerprintJPEG() {
        return rightThumbFingerprintJPEG;
    }

    /**
     * Sets the value of the rightThumbFingerprintJPEG property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setRightThumbFingerprintJPEG(byte[] value) {
        this.rightThumbFingerprintJPEG = value;
    }

    /**
     * Gets the value of the rightThumbFingerprintJPEG2000 property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getRightThumbFingerprintJPEG2000() {
        return rightThumbFingerprintJPEG2000;
    }

    /**
     * Sets the value of the rightThumbFingerprintJPEG2000 property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setRightThumbFingerprintJPEG2000(byte[] value) {
        this.rightThumbFingerprintJPEG2000 = value;
    }

    /**
     * Gets the value of the rightThumbFingerprintWSQ property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getRightThumbFingerprintWSQ() {
        return rightThumbFingerprintWSQ;
    }

    /**
     * Sets the value of the rightThumbFingerprintWSQ property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setRightThumbFingerprintWSQ(byte[] value) {
        this.rightThumbFingerprintWSQ = value;
    }

}
