//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.16 at 04:31:58 PM EET 
//


package se.snabbfoto.ejb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fingerprintQualityDecision complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fingerprintQualityDecision"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="duplicatedLeftHandFingerprints" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="duplicatedRightHandFingerprints" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="rejectedLeftHandFingerprints" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="rejectedRightHandFingerprints" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="result" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fingerprintQualityDecision", propOrder = {
    "duplicatedLeftHandFingerprints",
    "duplicatedRightHandFingerprints",
    "rejectedLeftHandFingerprints",
    "rejectedRightHandFingerprints",
    "result"
})
public class FingerprintQualityDecision
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    protected byte duplicatedLeftHandFingerprints;
    protected byte duplicatedRightHandFingerprints;
    protected byte rejectedLeftHandFingerprints;
    protected byte rejectedRightHandFingerprints;
    protected int result;

    /**
     * Gets the value of the duplicatedLeftHandFingerprints property.
     * 
     */
    public byte getDuplicatedLeftHandFingerprints() {
        return duplicatedLeftHandFingerprints;
    }

    /**
     * Sets the value of the duplicatedLeftHandFingerprints property.
     * 
     */
    public void setDuplicatedLeftHandFingerprints(byte value) {
        this.duplicatedLeftHandFingerprints = value;
    }

    /**
     * Gets the value of the duplicatedRightHandFingerprints property.
     * 
     */
    public byte getDuplicatedRightHandFingerprints() {
        return duplicatedRightHandFingerprints;
    }

    /**
     * Sets the value of the duplicatedRightHandFingerprints property.
     * 
     */
    public void setDuplicatedRightHandFingerprints(byte value) {
        this.duplicatedRightHandFingerprints = value;
    }

    /**
     * Gets the value of the rejectedLeftHandFingerprints property.
     * 
     */
    public byte getRejectedLeftHandFingerprints() {
        return rejectedLeftHandFingerprints;
    }

    /**
     * Sets the value of the rejectedLeftHandFingerprints property.
     * 
     */
    public void setRejectedLeftHandFingerprints(byte value) {
        this.rejectedLeftHandFingerprints = value;
    }

    /**
     * Gets the value of the rejectedRightHandFingerprints property.
     * 
     */
    public byte getRejectedRightHandFingerprints() {
        return rejectedRightHandFingerprints;
    }

    /**
     * Sets the value of the rejectedRightHandFingerprints property.
     * 
     */
    public void setRejectedRightHandFingerprints(byte value) {
        this.rejectedRightHandFingerprints = value;
    }

    /**
     * Gets the value of the result property.
     * 
     */
    public int getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     */
    public void setResult(int value) {
        this.result = value;
    }

}
