//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.16 at 04:31:58 PM EET 
//


package se.snabbfoto.ejb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for getFingerprintRecordQualityFromSet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getFingerprintRecordQualityFromSet"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="arg0" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="arg1" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="arg2" type="{http://ejb.snabbfoto.se/}fingerprint" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getFingerprintRecordQualityFromSet", propOrder = {
    "arg0",
    "arg1",
    "arg2"
})
@XmlRootElement(name = "getFingerprintRecordQualityFromSet")
public class GetFingerprintRecordQualityFromSet
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    protected byte arg0;
    protected byte arg1;
    protected Fingerprint arg2;

    /**
     * Gets the value of the arg0 property.
     * 
     */
    public byte getArg0() {
        return arg0;
    }

    /**
     * Sets the value of the arg0 property.
     * 
     */
    public void setArg0(byte value) {
        this.arg0 = value;
    }

    /**
     * Gets the value of the arg1 property.
     * 
     */
    public byte getArg1() {
        return arg1;
    }

    /**
     * Sets the value of the arg1 property.
     * 
     */
    public void setArg1(byte value) {
        this.arg1 = value;
    }

    /**
     * Gets the value of the arg2 property.
     * 
     * @return
     *     possible object is
     *     {@link Fingerprint }
     *     
     */
    public Fingerprint getArg2() {
        return arg2;
    }

    /**
     * Sets the value of the arg2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fingerprint }
     *     
     */
    public void setArg2(Fingerprint value) {
        this.arg2 = value;
    }

}
