//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.16 at 01:00:04 PM EET 
//


package se.snabbfoto.ejb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the se.snabbfoto.ejb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: se.snabbfoto.ejb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EnrollmentStationException }
     * 
     */
    public EnrollmentStationException createEnrollmentStationException() {
        return new EnrollmentStationException();
    }

    /**
     * Create an instance of {@link NonExistentPhotoException }
     * 
     */
    public NonExistentPhotoException createNonExistentPhotoException() {
        return new NonExistentPhotoException();
    }

    /**
     * Create an instance of {@link NonExistentSignatureException }
     * 
     */
    public NonExistentSignatureException createNonExistentSignatureException() {
        return new NonExistentSignatureException();
    }

    /**
     * Create an instance of {@link CapturePhoto }
     * 
     */
    public CapturePhoto createCapturePhoto() {
        return new CapturePhoto();
    }

    /**
     * Create an instance of {@link CapturePhotoResponse }
     * 
     */
    public CapturePhotoResponse createCapturePhotoResponse() {
        return new CapturePhotoResponse();
    }

    /**
     * Create an instance of {@link CaptureSignature }
     * 
     */
    public CaptureSignature createCaptureSignature() {
        return new CaptureSignature();
    }

    /**
     * Create an instance of {@link CaptureSignatureResponse }
     * 
     */
    public CaptureSignatureResponse createCaptureSignatureResponse() {
        return new CaptureSignatureResponse();
    }

    /**
     * Create an instance of {@link DeletePersonalFiles }
     * 
     */
    public DeletePersonalFiles createDeletePersonalFiles() {
        return new DeletePersonalFiles();
    }

    /**
     * Create an instance of {@link DeletePersonalFilesResponse }
     * 
     */
    public DeletePersonalFilesResponse createDeletePersonalFilesResponse() {
        return new DeletePersonalFilesResponse();
    }

    /**
     * Create an instance of {@link GenerateTokenPhoto }
     * 
     */
    public GenerateTokenPhoto createGenerateTokenPhoto() {
        return new GenerateTokenPhoto();
    }

    /**
     * Create an instance of {@link Point }
     * 
     */
    public Point createPoint() {
        return new Point();
    }

    /**
     * Create an instance of {@link GenerateTokenPhotoResponse }
     * 
     */
    public GenerateTokenPhotoResponse createGenerateTokenPhotoResponse() {
        return new GenerateTokenPhotoResponse();
    }

    /**
     * Create an instance of {@link Photo }
     * 
     */
    public Photo createPhoto() {
        return new Photo();
    }

    /**
     * Create an instance of {@link GetBasePhoto }
     * 
     */
    public GetBasePhoto createGetBasePhoto() {
        return new GetBasePhoto();
    }

    /**
     * Create an instance of {@link GetBasePhotoResponse }
     * 
     */
    public GetBasePhotoResponse createGetBasePhotoResponse() {
        return new GetBasePhotoResponse();
    }

    /**
     * Create an instance of {@link GetEnrollmentStationIdentity }
     * 
     */
    public GetEnrollmentStationIdentity createGetEnrollmentStationIdentity() {
        return new GetEnrollmentStationIdentity();
    }

    /**
     * Create an instance of {@link GetEnrollmentStationIdentityResponse }
     * 
     */
    public GetEnrollmentStationIdentityResponse createGetEnrollmentStationIdentityResponse() {
        return new GetEnrollmentStationIdentityResponse();
    }

    /**
     * Create an instance of {@link GetFaceImageQuality }
     * 
     */
    public GetFaceImageQuality createGetFaceImageQuality() {
        return new GetFaceImageQuality();
    }

    /**
     * Create an instance of {@link GetFaceImageQualityExtended }
     * 
     */
    public GetFaceImageQualityExtended createGetFaceImageQualityExtended() {
        return new GetFaceImageQualityExtended();
    }

    /**
     * Create an instance of {@link GetFaceImageQualityExtendedResponse }
     * 
     */
    public GetFaceImageQualityExtendedResponse createGetFaceImageQualityExtendedResponse() {
        return new GetFaceImageQualityExtendedResponse();
    }

    /**
     * Create an instance of {@link FaceImageQualityExtended }
     * 
     */
    public FaceImageQualityExtended createFaceImageQualityExtended() {
        return new FaceImageQualityExtended();
    }

    /**
     * Create an instance of {@link GetFaceImageQualityResponse }
     * 
     */
    public GetFaceImageQualityResponse createGetFaceImageQualityResponse() {
        return new GetFaceImageQualityResponse();
    }

    /**
     * Create an instance of {@link FaceImageQuality }
     * 
     */
    public FaceImageQuality createFaceImageQuality() {
        return new FaceImageQuality();
    }

    /**
     * Create an instance of {@link GetFullFrontal }
     * 
     */
    public GetFullFrontal createGetFullFrontal() {
        return new GetFullFrontal();
    }

    /**
     * Create an instance of {@link GetFullFrontalResponse }
     * 
     */
    public GetFullFrontalResponse createGetFullFrontalResponse() {
        return new GetFullFrontalResponse();
    }

    /**
     * Create an instance of {@link GetHeight }
     * 
     */
    public GetHeight createGetHeight() {
        return new GetHeight();
    }

    /**
     * Create an instance of {@link GetHeightResponse }
     * 
     */
    public GetHeightResponse createGetHeightResponse() {
        return new GetHeightResponse();
    }

    /**
     * Create an instance of {@link GetLastErrorMessage }
     * 
     */
    public GetLastErrorMessage createGetLastErrorMessage() {
        return new GetLastErrorMessage();
    }

    /**
     * Create an instance of {@link GetLastErrorMessageResponse }
     * 
     */
    public GetLastErrorMessageResponse createGetLastErrorMessageResponse() {
        return new GetLastErrorMessageResponse();
    }

    /**
     * Create an instance of {@link GetPhoto }
     * 
     */
    public GetPhoto createGetPhoto() {
        return new GetPhoto();
    }

    /**
     * Create an instance of {@link GetPhotoResponse }
     * 
     */
    public GetPhotoResponse createGetPhotoResponse() {
        return new GetPhotoResponse();
    }

    /**
     * Create an instance of {@link GetRawPhoto }
     * 
     */
    public GetRawPhoto createGetRawPhoto() {
        return new GetRawPhoto();
    }

    /**
     * Create an instance of {@link GetRawPhotoResponse }
     * 
     */
    public GetRawPhotoResponse createGetRawPhotoResponse() {
        return new GetRawPhotoResponse();
    }

    /**
     * Create an instance of {@link GetSignature }
     * 
     */
    public GetSignature createGetSignature() {
        return new GetSignature();
    }

    /**
     * Create an instance of {@link GetSignatureResponse }
     * 
     */
    public GetSignatureResponse createGetSignatureResponse() {
        return new GetSignatureResponse();
    }

    /**
     * Create an instance of {@link Signature }
     * 
     */
    public Signature createSignature() {
        return new Signature();
    }

    /**
     * Create an instance of {@link GetVersion }
     * 
     */
    public GetVersion createGetVersion() {
        return new GetVersion();
    }

    /**
     * Create an instance of {@link GetVersionResponse }
     * 
     */
    public GetVersionResponse createGetVersionResponse() {
        return new GetVersionResponse();
    }

    /**
     * Create an instance of {@link IsEnrollmentStationOk }
     * 
     */
    public IsEnrollmentStationOk createIsEnrollmentStationOk() {
        return new IsEnrollmentStationOk();
    }

    /**
     * Create an instance of {@link IsEnrollmentStationOkResponse }
     * 
     */
    public IsEnrollmentStationOkResponse createIsEnrollmentStationOkResponse() {
        return new IsEnrollmentStationOkResponse();
    }

    /**
     * Create an instance of {@link IsPhotoObjectTooClose }
     * 
     */
    public IsPhotoObjectTooClose createIsPhotoObjectTooClose() {
        return new IsPhotoObjectTooClose();
    }

    /**
     * Create an instance of {@link IsPhotoObjectTooCloseResponse }
     * 
     */
    public IsPhotoObjectTooCloseResponse createIsPhotoObjectTooCloseResponse() {
        return new IsPhotoObjectTooCloseResponse();
    }

    /**
     * Create an instance of {@link MoveDown }
     * 
     */
    public MoveDown createMoveDown() {
        return new MoveDown();
    }

    /**
     * Create an instance of {@link MoveDownResponse }
     * 
     */
    public MoveDownResponse createMoveDownResponse() {
        return new MoveDownResponse();
    }

    /**
     * Create an instance of {@link MoveUp }
     * 
     */
    public MoveUp createMoveUp() {
        return new MoveUp();
    }

    /**
     * Create an instance of {@link MoveUpResponse }
     * 
     */
    public MoveUpResponse createMoveUpResponse() {
        return new MoveUpResponse();
    }

    /**
     * Create an instance of {@link PlaySound }
     * 
     */
    public PlaySound createPlaySound() {
        return new PlaySound();
    }

    /**
     * Create an instance of {@link PlaySoundResponse }
     * 
     */
    public PlaySoundResponse createPlaySoundResponse() {
        return new PlaySoundResponse();
    }

    /**
     * Create an instance of {@link SetHeight }
     * 
     */
    public SetHeight createSetHeight() {
        return new SetHeight();
    }

    /**
     * Create an instance of {@link SetHeightAutomatically }
     * 
     */
    public SetHeightAutomatically createSetHeightAutomatically() {
        return new SetHeightAutomatically();
    }

    /**
     * Create an instance of {@link SetHeightAutomaticallyResponse }
     * 
     */
    public SetHeightAutomaticallyResponse createSetHeightAutomaticallyResponse() {
        return new SetHeightAutomaticallyResponse();
    }

    /**
     * Create an instance of {@link SetHeightResponse }
     * 
     */
    public SetHeightResponse createSetHeightResponse() {
        return new SetHeightResponse();
    }

    /**
     * Create an instance of {@link SetLight }
     * 
     */
    public SetLight createSetLight() {
        return new SetLight();
    }

    /**
     * Create an instance of {@link SetLightResponse }
     * 
     */
    public SetLightResponse createSetLightResponse() {
        return new SetLightResponse();
    }

    /**
     * Create an instance of {@link ShowDefaultScreen }
     * 
     */
    public ShowDefaultScreen createShowDefaultScreen() {
        return new ShowDefaultScreen();
    }

    /**
     * Create an instance of {@link ShowDefaultScreenResponse }
     * 
     */
    public ShowDefaultScreenResponse createShowDefaultScreenResponse() {
        return new ShowDefaultScreenResponse();
    }

    /**
     * Create an instance of {@link ShowInformation }
     * 
     */
    public ShowInformation createShowInformation() {
        return new ShowInformation();
    }

    /**
     * Create an instance of {@link ShowInformationResponse }
     * 
     */
    public ShowInformationResponse createShowInformationResponse() {
        return new ShowInformationResponse();
    }

    /**
     * Create an instance of {@link ShowPhoto }
     * 
     */
    public ShowPhoto createShowPhoto() {
        return new ShowPhoto();
    }

    /**
     * Create an instance of {@link ShowPhotoResponse }
     * 
     */
    public ShowPhotoResponse createShowPhotoResponse() {
        return new ShowPhotoResponse();
    }

    /**
     * Create an instance of {@link ShowPreview }
     * 
     */
    public ShowPreview createShowPreview() {
        return new ShowPreview();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link ShowPreviewResponse }
     * 
     */
    public ShowPreviewResponse createShowPreviewResponse() {
        return new ShowPreviewResponse();
    }

    /**
     * Create an instance of {@link Shutdown }
     * 
     */
    public Shutdown createShutdown() {
        return new Shutdown();
    }

    /**
     * Create an instance of {@link ShutdownResponse }
     * 
     */
    public ShutdownResponse createShutdownResponse() {
        return new ShutdownResponse();
    }

    /**
     * Create an instance of {@link StartViewfinder }
     * 
     */
    public StartViewfinder createStartViewfinder() {
        return new StartViewfinder();
    }

    /**
     * Create an instance of {@link StartViewfinderResponse }
     * 
     */
    public StartViewfinderResponse createStartViewfinderResponse() {
        return new StartViewfinderResponse();
    }

    /**
     * Create an instance of {@link StopMovement }
     * 
     */
    public StopMovement createStopMovement() {
        return new StopMovement();
    }

    /**
     * Create an instance of {@link StopMovementResponse }
     * 
     */
    public StopMovementResponse createStopMovementResponse() {
        return new StopMovementResponse();
    }

    /**
     * Create an instance of {@link StopViewfinder }
     * 
     */
    public StopViewfinder createStopViewfinder() {
        return new StopViewfinder();
    }

    /**
     * Create an instance of {@link StopViewfinderResponse }
     * 
     */
    public StopViewfinderResponse createStopViewfinderResponse() {
        return new StopViewfinderResponse();
    }

    /**
     * Create an instance of {@link UploadImageFile }
     * 
     */
    public UploadImageFile createUploadImageFile() {
        return new UploadImageFile();
    }

    /**
     * Create an instance of {@link UploadImageFileResponse }
     * 
     */
    public UploadImageFileResponse createUploadImageFileResponse() {
        return new UploadImageFileResponse();
    }

    public NonExistentFingerprintException createNonExistentFingerprintException() {
        return new NonExistentFingerprintException();
    }

    /**
     * Create an instance of {@link CancelFingerprint }
     *
     */
    public CancelFingerprint createCancelFingerprint() {
        return new CancelFingerprint();
    }

    /**
     * Create an instance of {@link CancelFingerprintResponse }
     *
     */
    public CancelFingerprintResponse createCancelFingerprintResponse() {
        return new CancelFingerprintResponse();
    }

    /**
     * Create an instance of {@link CaptureFingerprints }
     *
     */
    public CaptureFingerprints createCaptureFingerprints() {
        return new CaptureFingerprints();
    }

    /**
     * Create an instance of {@link CaptureFingerprintsResponse }
     *
     */
    public CaptureFingerprintsResponse createCaptureFingerprintsResponse() {
        return new CaptureFingerprintsResponse();
    }

    /**
     * Create an instance of {@link GetFingerprintDeviceInformation }
     *
     */
    public GetFingerprintDeviceInformation createGetFingerprintDeviceInformation() {
        return new GetFingerprintDeviceInformation();
    }

    /**
     * Create an instance of {@link GetFingerprintDeviceInformationResponse }
     *
     */
    public GetFingerprintDeviceInformationResponse createGetFingerprintDeviceInformationResponse() {
        return new GetFingerprintDeviceInformationResponse();
    }

    /**
     * Create an instance of {@link FingerprintDeviceInformation }
     *
     */
    public FingerprintDeviceInformation createFingerprintDeviceInformation() {
        return new FingerprintDeviceInformation();
    }

    /**
     * Create an instance of {@link GetFingerprintRecordQuality }
     *
     */
    public GetFingerprintRecordQuality createGetFingerprintRecordQuality() {
        return new GetFingerprintRecordQuality();
    }

    /**
     * Create an instance of {@link GetFingerprintRecordQualityFromSet }
     *
     */
    public GetFingerprintRecordQualityFromSet createGetFingerprintRecordQualityFromSet() {
        return new GetFingerprintRecordQualityFromSet();
    }

    /**
     * Create an instance of {@link Fingerprint }
     *
     */
    public Fingerprint createFingerprint() {
        return new Fingerprint();
    }

    /**
     * Create an instance of {@link GetFingerprintRecordQualityFromSetResponse }
     *
     */
    public GetFingerprintRecordQualityFromSetResponse createGetFingerprintRecordQualityFromSetResponse() {
        return new GetFingerprintRecordQualityFromSetResponse();
    }

    /**
     * Create an instance of {@link FingerprintQualityDecision }
     *
     */
    public FingerprintQualityDecision createFingerprintQualityDecision() {
        return new FingerprintQualityDecision();
    }

    /**
     * Create an instance of {@link GetFingerprintRecordQualityResponse }
     *
     */
    public GetFingerprintRecordQualityResponse createGetFingerprintRecordQualityResponse() {
        return new GetFingerprintRecordQualityResponse();
    }

    /**
     * Create an instance of {@link GetFingerprints }
     *
     */
    public GetFingerprints createGetFingerprints() {
        return new GetFingerprints();
    }

    /**
     * Create an instance of {@link GetFingerprintsResponse }
     *
     */
    public GetFingerprintsResponse createGetFingerprintsResponse() {
        return new GetFingerprintsResponse();
    }

    /**
     * Create an instance of {@link SetFingerprintInstruction }
     *
     */
    public SetFingerprintInstruction createSetFingerprintInstruction() {
        return new SetFingerprintInstruction();
    }

    /**
     * Create an instance of {@link SetFingerprintInstructionResponse }
     *
     */
    public SetFingerprintInstructionResponse createSetFingerprintInstructionResponse() {
        return new SetFingerprintInstructionResponse();
    }

}
