//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.16 at 01:00:04 PM EET 
//


package se.snabbfoto.ejb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for photo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="photo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="compressedFormat" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="compressedPhoto" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="format" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="photo" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "photo", propOrder = {
    "compressedFormat",
    "compressedPhoto",
    "format",
    "photo"
})
public class Photo
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    protected int compressedFormat;
    protected byte[] compressedPhoto;
    protected int format;
    protected byte[] photo;

    /**
     * Gets the value of the compressedFormat property.
     * 
     */
    public int getCompressedFormat() {
        return compressedFormat;
    }

    /**
     * Sets the value of the compressedFormat property.
     * 
     */
    public void setCompressedFormat(int value) {
        this.compressedFormat = value;
    }

    /**
     * Gets the value of the compressedPhoto property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getCompressedPhoto() {
        return compressedPhoto;
    }

    /**
     * Sets the value of the compressedPhoto property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setCompressedPhoto(byte[] value) {
        this.compressedPhoto = value;
    }

    /**
     * Gets the value of the format property.
     * 
     */
    public int getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     */
    public void setFormat(int value) {
        this.format = value;
    }

    /**
     * Gets the value of the photo property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getPhoto() {
        return photo;
    }

    /**
     * Sets the value of the photo property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setPhoto(byte[] value) {
        this.photo = value;
    }

}
