client:
  default-uri: http://192.168.0.10:8080/EnrollmentStation-EnrollmentEJB/EnrollmentServiceImpl?wsdl
  signature:
    key-store: classpath:keys/client.p12
    key-store-password: 123qweASD
    key-alias: client
    key-password: 123qweASD
