//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.16 at 01:00:04 PM EET 
//

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;

import se.snabbfoto.ejb.*;

public class JAXBDebug {


    public static JAXBContext createContext(ClassLoader classLoader)
        throws JAXBException
    {
        return JAXBContext.newInstance(
                EnrollmentStationException.class,
                NonExistentPhotoException.class,
                NonExistentSignatureException.class,
                CapturePhoto.class,
                CapturePhotoResponse.class,
                CaptureSignature.class,
                CaptureSignatureResponse.class,
                DeletePersonalFiles.class,
                DeletePersonalFilesResponse.class,
                GenerateTokenPhoto.class,
                Point.class,
                GenerateTokenPhotoResponse.class,
                Photo.class,
                GetBasePhoto.class,
                GetBasePhotoResponse.class,
                GetEnrollmentStationIdentity.class,
                GetEnrollmentStationIdentityResponse.class,
                GetFaceImageQuality.class,
                GetFaceImageQualityExtended.class,
                GetFaceImageQualityExtendedResponse.class,
                FaceImageQualityExtended.class,
                GetFaceImageQualityResponse.class,
                FaceImageQuality.class,
                GetFullFrontal.class,
                GetFullFrontalResponse.class,
                GetHeight.class,
                GetHeightResponse.class,
                GetLastErrorMessage.class,
                GetLastErrorMessageResponse.class,
                GetPhoto.class,
                GetPhotoResponse.class,
                GetRawPhoto.class,
                GetRawPhotoResponse.class,
                GetSignature.class,
                GetSignatureResponse.class,
                Signature.class,
                GetVersion.class,
                GetVersionResponse.class,
                IsEnrollmentStationOk.class,
                IsEnrollmentStationOkResponse.class,
                IsPhotoObjectTooClose.class,
                IsPhotoObjectTooCloseResponse.class,
                MoveDown.class,
                MoveDownResponse.class,
                MoveUp.class,
                MoveUpResponse.class,
                PlaySound.class,
                PlaySoundResponse.class,
                SetHeight.class,
                SetHeightAutomatically.class,
                SetHeightAutomaticallyResponse.class,
                SetHeightResponse.class,
                SetLight.class,
                SetLightResponse.class,
                ShowDefaultScreen.class,
                ShowDefaultScreenResponse.class,
                ShowInformation.class,
                ShowInformationResponse.class,
                ShowPhoto.class,
                ShowPhotoResponse.class,
                ShowPreview.class,
                Person.class,
                ShowPreviewResponse.class,
                Shutdown.class,
                ShutdownResponse.class,
                StartViewfinder.class,
                StartViewfinderResponse.class,
                StopMovement.class,
                StopMovementResponse.class,
                StopViewfinder.class,
                StopViewfinderResponse.class,
                UploadImageFile.class,
                UploadImageFileResponse.class,
                NonExistentFingerprintException.class,
                CancelFingerprint.class,
                CancelFingerprintResponse.class,
                CaptureFingerprints.class,
                CaptureFingerprintsResponse.class,
                GetFingerprintDeviceInformation.class,
                GetFingerprintDeviceInformationResponse.class,
                FingerprintDeviceInformation.class,
                GetFingerprintRecordQuality.class,
                GetFingerprintRecordQualityFromSet.class,
                Fingerprint.class,
                GetFingerprintRecordQualityFromSetResponse.class,
                FingerprintQualityDecision.class,
                GetFingerprintRecordQualityResponse.class,
                GetFingerprints.class,
                GetFingerprintsResponse.class,
                SetFingerprintInstruction.class,
                SetFingerprintInstructionResponse.class,
                ObjectFactory.class
        );
    }

}
