//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.16 at 01:00:04 PM EET 
//

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import se.snabbfoto.ejb.CapturePhoto;
import se.snabbfoto.ejb.CapturePhotoResponse;
import se.snabbfoto.ejb.CaptureSignature;
import se.snabbfoto.ejb.CaptureSignatureResponse;
import se.snabbfoto.ejb.DeletePersonalFiles;
import se.snabbfoto.ejb.DeletePersonalFilesResponse;
import se.snabbfoto.ejb.EnrollmentStationException;
import se.snabbfoto.ejb.FaceImageQuality;
import se.snabbfoto.ejb.FaceImageQualityExtended;
import se.snabbfoto.ejb.GenerateTokenPhoto;
import se.snabbfoto.ejb.GenerateTokenPhotoResponse;
import se.snabbfoto.ejb.GetBasePhoto;
import se.snabbfoto.ejb.GetBasePhotoResponse;
import se.snabbfoto.ejb.GetEnrollmentStationIdentity;
import se.snabbfoto.ejb.GetEnrollmentStationIdentityResponse;
import se.snabbfoto.ejb.GetFaceImageQuality;
import se.snabbfoto.ejb.GetFaceImageQualityExtended;
import se.snabbfoto.ejb.GetFaceImageQualityExtendedResponse;
import se.snabbfoto.ejb.GetFaceImageQualityResponse;
import se.snabbfoto.ejb.GetFullFrontal;
import se.snabbfoto.ejb.GetFullFrontalResponse;
import se.snabbfoto.ejb.GetHeight;
import se.snabbfoto.ejb.GetHeightResponse;
import se.snabbfoto.ejb.GetLastErrorMessage;
import se.snabbfoto.ejb.GetLastErrorMessageResponse;
import se.snabbfoto.ejb.GetPhoto;
import se.snabbfoto.ejb.GetPhotoResponse;
import se.snabbfoto.ejb.GetRawPhoto;
import se.snabbfoto.ejb.GetRawPhotoResponse;
import se.snabbfoto.ejb.GetSignature;
import se.snabbfoto.ejb.GetSignatureResponse;
import se.snabbfoto.ejb.GetVersion;
import se.snabbfoto.ejb.GetVersionResponse;
import se.snabbfoto.ejb.IsEnrollmentStationOk;
import se.snabbfoto.ejb.IsEnrollmentStationOkResponse;
import se.snabbfoto.ejb.IsPhotoObjectTooClose;
import se.snabbfoto.ejb.IsPhotoObjectTooCloseResponse;
import se.snabbfoto.ejb.MoveDown;
import se.snabbfoto.ejb.MoveDownResponse;
import se.snabbfoto.ejb.MoveUp;
import se.snabbfoto.ejb.MoveUpResponse;
import se.snabbfoto.ejb.NonExistentPhotoException;
import se.snabbfoto.ejb.NonExistentSignatureException;
import se.snabbfoto.ejb.ObjectFactory;
import se.snabbfoto.ejb.Person;
import se.snabbfoto.ejb.Photo;
import se.snabbfoto.ejb.PlaySound;
import se.snabbfoto.ejb.PlaySoundResponse;
import se.snabbfoto.ejb.Point;
import se.snabbfoto.ejb.SetHeight;
import se.snabbfoto.ejb.SetHeightAutomatically;
import se.snabbfoto.ejb.SetHeightAutomaticallyResponse;
import se.snabbfoto.ejb.SetHeightResponse;
import se.snabbfoto.ejb.SetLight;
import se.snabbfoto.ejb.SetLightResponse;
import se.snabbfoto.ejb.ShowDefaultScreen;
import se.snabbfoto.ejb.ShowDefaultScreenResponse;
import se.snabbfoto.ejb.ShowInformation;
import se.snabbfoto.ejb.ShowInformationResponse;
import se.snabbfoto.ejb.ShowPhoto;
import se.snabbfoto.ejb.ShowPhotoResponse;
import se.snabbfoto.ejb.ShowPreview;
import se.snabbfoto.ejb.ShowPreviewResponse;
import se.snabbfoto.ejb.Shutdown;
import se.snabbfoto.ejb.ShutdownResponse;
import se.snabbfoto.ejb.Signature;
import se.snabbfoto.ejb.StartViewfinder;
import se.snabbfoto.ejb.StartViewfinderResponse;
import se.snabbfoto.ejb.StopMovement;
import se.snabbfoto.ejb.StopMovementResponse;
import se.snabbfoto.ejb.StopViewfinder;
import se.snabbfoto.ejb.StopViewfinderResponse;
import se.snabbfoto.ejb.UploadImageFile;
import se.snabbfoto.ejb.UploadImageFileResponse;

public class JAXBDebug {


    public static JAXBContext createContext(ClassLoader classLoader)
        throws JAXBException
    {
        return JAXBContext.newInstance(EnrollmentStationException.class, NonExistentPhotoException.class, NonExistentSignatureException.class, CapturePhoto.class, CapturePhotoResponse.class, CaptureSignature.class, CaptureSignatureResponse.class, DeletePersonalFiles.class, DeletePersonalFilesResponse.class, GenerateTokenPhoto.class, Point.class, GenerateTokenPhotoResponse.class, Photo.class, GetBasePhoto.class, GetBasePhotoResponse.class, GetEnrollmentStationIdentity.class, GetEnrollmentStationIdentityResponse.class, GetFaceImageQuality.class, GetFaceImageQualityExtended.class, GetFaceImageQualityExtendedResponse.class, FaceImageQualityExtended.class, GetFaceImageQualityResponse.class, FaceImageQuality.class, GetFullFrontal.class, GetFullFrontalResponse.class, GetHeight.class, GetHeightResponse.class, GetLastErrorMessage.class, GetLastErrorMessageResponse.class, GetPhoto.class, GetPhotoResponse.class, GetRawPhoto.class, GetRawPhotoResponse.class, GetSignature.class, GetSignatureResponse.class, Signature.class, GetVersion.class, GetVersionResponse.class, IsEnrollmentStationOk.class, IsEnrollmentStationOkResponse.class, IsPhotoObjectTooClose.class, IsPhotoObjectTooCloseResponse.class, MoveDown.class, MoveDownResponse.class, MoveUp.class, MoveUpResponse.class, PlaySound.class, PlaySoundResponse.class, SetHeight.class, SetHeightAutomatically.class, SetHeightAutomaticallyResponse.class, SetHeightResponse.class, SetLight.class, SetLightResponse.class, ShowDefaultScreen.class, ShowDefaultScreenResponse.class, ShowInformation.class, ShowInformationResponse.class, ShowPhoto.class, ShowPhotoResponse.class, ShowPreview.class, Person.class, ShowPreviewResponse.class, Shutdown.class, ShutdownResponse.class, StartViewfinder.class, StartViewfinderResponse.class, StopMovement.class, StopMovementResponse.class, StopViewfinder.class, StopViewfinderResponse.class, UploadImageFile.class, UploadImageFileResponse.class, ObjectFactory.class);
    }

}
